language: php

php: 
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6 --prefer-source --no-interaction --dev
#php ocular.phar code-coverage:upload --access-token="your-token" --format=php-clover coverage.clover
script: phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v